title: "Building Brain Computer Interfaces (BCIs) using deep generative models"
student: "Ulysse DURAND\\\\Centrale Lyon"
tutor: "Nidhi GOYAL, Assistant Professor School of Engineering Mahindra University"
UE: "Application Internship Report"
subject: "Mahindra University - Hyderabad, India"